apiVersion: v1
kind: Pod
metadata:
  name: color-app-configmap
  labels: 
    app: colorapp
spec:
  containers:
  - image: 616865343531.dkr.ecr.us-east-1.amazonaws.com/assignment3:color
    env:
    # It will accept APP_COLOR as environment variable (Line 39 app.py)
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: app-config
          key: COLOR_ENV
    name: color-app-configmap
    ports:
    - containerPort: 8080
      protocol: TCP