apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb
