apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: backend
  name: mongo-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi